name: release

on:
  push:
    tags: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v -o nginx-goldap ./...
    
    - name: debian
      id: debian
      uses: osallou/deb-package-action@bullseye

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          nginx-goldap
          *.deb