name: release

on:
  push:
    tags: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: debian
      id: debian
      uses: genouest/deb-package-action@bookworm

    - name: Build
      run: go build -v -o nginx-goldap *.go

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          nginx-goldap
          *.deb
